version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: db_name
      MYSQL_DATABASE: db_name
    volumes:
      - db-data-idade:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_NAME: db_name
    ports:
      - "5000:5000"
    depends_on:
      - db
    secrets:
      - mysql_root_password
      - mysql_password

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on: 
      - backend

volumes:
  db-data-idade:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

networks:
  default:
    name: idade-network
